[package]
name = "keymap"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
misskey = { git = "https://github.com/poppingmoon/misskey-rs/", branch = "feature/13.14.0" }
tokio = { version = "1.42.0", features = ["full"] }
